"""empty message

Revision ID: c09aef3529cf
Revises: 5d52372d4bec
Create Date: 2023-06-23 00:02:38.465344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09aef3529cf'
down_revision = '5d52372d4bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_question'),
    sa.UniqueConstraint('create_date', name='uq_question_create_date'),
    sa.UniqueConstraint('subject', name='uq_question_subject')
    )
    # ### end Alembic commands ###
